services:
  backend:
    build: ./backend/simpleapi
    container_name: backend-app
    networks:
      - network-app
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./backend/simpleapi/.env

  database:
    build: ./database
    container_name: postgres-db
    networks:
      - network-app
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd

  httpd:
    build: ./httpserver
    container_name: reverse-proxy
    ports:
      - "8080:80"
    networks:
      - network-app
    depends_on:
      - backend

networks:
  network-app:
    driver: bridge

volumes:
  db-data: